### ISSUE TITLE
Crash upon clicking on an icon on android

### ISSUE THREAD

**Issue by FRBFStudios** [Rynat86/Better-Unlock-Info#4]
[Crash 2024-05-25 14.02.12.dmp](https://github.com/Rynat86/Better-Unlock-Info/files/15443135/Crash.2024-05-25.14.02.12.dmp)
(I am reporting this here since I currently don't have access to Discord)
When clicking on an icon in the Garage, locked or unlocked, the game crashes on my android phone, which doesn't happen anymore after disabling/uninstalling the mod. Thank you in advance, your mod is very useful and cool! 
I've attached the crashlog; and since this could be a compatibility issue here is a list of my installed mods:

Geode
Advanced Song Search
Animated Profile icons
AutoSong
Better Progression
BetterEdit
BetterInfo
BetterSave
Better Unlock Info
BetterPause
Better Icon Randomizer
Brightness Mod
ChangeFont19
Circle Tool
Cleaner Menu
Click between Steps
Compact Editor Menus
Colored Icon Kit
Coins in Pause Menu
Congregation Jumpscare
Creator Layer Randomizer
Death Tracker
Easing Preview
Editor Sounds
Emojis in Comments
ErysEdits
EzClipboard
Garage Utilities
Garage in Editor
GDDP Integration
GD utils
GDDL Integration
GDShare
GMD API
GoldenBest
Happy Textures :3
Heart Attack
High Graphics on Android
Hide Locks
Icon Profile 2.2
Icon Save 2.2
IDs integration
Jukebox
Level Info in Pause Menu
Level Thumbnails
Level Pronouns
Level Ratings
Level History
Misc Bugfixes
More Object Info
More Settings Button
More Difficulties
Na Demon
NLW integration
NoEditTabSwitch
NoMoreGames
Node IDs
Percentage Bugfix
Projected Stars
Prism Menu
Restart Buttons
Run Info
Seperate Dual Icons
Skip Editor Save Confirm
Smooth Particles
StartPos switcher
Texture Loader
Texture Workshop
Treasure Checklist
User Reviews
XDbot
XXLify
YouTubers

**Comment by Rynat86** [comment]
hi, the android version is broken rn and I'm looking into it, ty for the log

**Comment by Rynat86** [comment]
the fix is out
