### ISSUE TITLE
Incompatible with Animated Profile Icons

### ISSUE THREAD

**Issue by FRBFStudios** [Rynat86/Better-Unlock-Info#5]
I installed Animated Profile Icons since it just got available for 2.206 and now my game crashes every time I view my profile. I reported this crash to the Geode Discord Server and they told me that it was because of BUI and that mod being incompatible
Crashlog:
[2024-08-17_17-17-23.txt](https://github.com/user-attachments/files/16645416/2024-08-17_17-17-23.txt)

**Comment by Rynat86** [comment]
pushed an update to fix the crashes, just gotta wait for animated profiles to update
